name: MinecraftTelepathy
version: '${project.version}'
main: org.cyci.mc.minecrafttelepathy.Registry
api-version: '1.21'

softdepend:
  - PlaceholderAPI

commands:
  telepathy:
    description: The main Telepathy command
    aliases: [ mtp ]
    usage: /telepathy
    permission: *
    permission-message: You don't have permission to use this command.
  friend:
    description: The friend command for MinecraftTelepathy
  party:
    description: The party command for MinecraftTelepathy