name: MinecraftTelepathy
version: '${project.version}'
main: org.cyci.mc.minecrafttelepathy.Registry
api-version: '1.21'

softdepend:
  - PlaceholderAPI

commands:
  example:
    description: An example command
    aliases: [ ex ]
    usage: /example
    permission: example.use
    permission-message: You don't have permission to use this command.
