name: MinecraftTelepathy
version: '1.0-SNAPSHOT'
main: org.cyci.mc.minecrafttelepathy.Registry
api-version: '1.21'

softdepend:
  - PlaceholderAPI

commands:
  telepathy:
    description: The main Telepathy command
    aliases: [ mtp ]
    usage: /telepathy
    permission: *
    permission-message: You don't have permission to use this command.
